// Shared emoji-icon lookup for tool cards (MoreToolsGrid, RelatedTools) so the
// same tool always gets the same icon everywhere it's shown.
export const TOOL_ICON_BY_SLUG: Record<string, string> = {
  "water-eject": "💧",
  "deep-speaker-cleaner": "🌊",
  "earpiece-speaker-cleaner": "📞",
  "speaker-dust-remover": "🧹",
  "left-right-speaker-test": "↔️",
  "speaker-test": "🔊",
  "mic-test": "🎙️",
  "tone-generator": "🎵",
  "bass-test": "🥁",
  "headphone-test": "🎧",
  "db-meter": "📊",
  "hearing-test": "👂",
  "noise-generator": "📻",
  "frequency-sweep": "📈",
  "webcam-test": "📷",
  "keyboard-tester": "⌨️",
  "dead-pixel-test": "🖥️",
  "touch-screen-test": "👆",
  tuner: "🎸",
  metronome: "⏱️",
  "bpm-counter": "👇",
  "cps-test": "🖱️",
  "typing-speed-test": "⌨️",
  "sleep-focus-sounds": "🌙",
  "safe-volume-calculator": "🦻",
  "text-to-speech": "🗣️",
  "audio-recorder": "🎙️",
  "vibration-test": "📳",
  "speaker-polarity-test": "🔄",
  "surround-sound-test": "🎬",
  "watch-water-eject": "⌚",
  "virtual-piano": "🎹",
  "camera-mic-test": "🎥",
};
